// Generated by LiveScript 1.2.0
describe('just.camelize', function(){
  var x$;
  x$ = it;
  x$('should camelCase dash-separted names', function(){
    expect(just.camelize('foo-bar')).toBe('fooBar');
  });
  x$('should camelCase with more than one dash', function(){
    expect(just.camelize('foo-bar-baz')).toBe('fooBarBaz');
  });
  x$('should work with underscores', function(){
    expect(just.camelize('foo_bar')).toBe('fooBar');
  });
  x$('should work with mixed underscore and dash', function(){
    expect(just.camelize('foo_bar-baz')).toBe('fooBarBaz');
  });
});