// Generated by LiveScript 1.2.0
describe('just.remove', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"for-removal\"></p>\n<div class=\"for-removal\"></div>\n<div class=\"for-removal\"></div>\n<div class=\"for-removal\"></div>");
  });
  x$('should remove an element', function(){
    just.remove(just.byId('for-removal', false));
    expect(just.byId('for-removal')).not.toExist();
  });
  x$('should remove an array of elements', function(){
    var el;
    just.remove(just.byClass('for-removal', document));
    el = just.byClass;
    expect(el.length).toEqual(0);
  });
});
describe('just.css', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<div id=\"style\"></div>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should define styles on element', function(){
    var el;
    el = just.byId('style');
    just.css('margin', '2px', el);
    expect(el.style.margin).toEqual('2px');
  });
  x$('should normalize style names', function(){
    var el;
    el = just.byId('style');
    just.css('margin-right', '4px', el);
    expect(el.style.marginRight).toEqual('4px');
  });
  x$('should not set bogus styles', function(){
    var el;
    el = just.byId('style');
    just.css('foo', 'bar', el);
    expect(el.style.foo).not.toBeDefined();
  });
  x$('should be curried', function(){
    var el, padding, hide;
    el = just.byId('style');
    padding = just.css('padding');
    hide = just.css('display', 'none');
    expect(el.style.padding).toEqual('');
    expect(el.style.display).toEqual('');
    padding('12px', el);
    expect(el.style.padding).toEqual('12px');
    expect(el.style.display).toEqual('');
    hide(el);
    expect(el.style.display).toEqual('none');
  });
});
describe('just.addClass', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"addclass\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should add a class name to element', function(){
    var el;
    el = just.byId('addclass');
    just.addClass('foo', el);
    expect(el).toHaveClass('foo');
  });
  x$('should be curried', function(){
    var addBar, el;
    addBar = just.addClass('bar');
    el = just.byId('addclass');
    addBar(el);
    expect(el).toHaveClass('bar');
  });
  x$('should add multiple classes', function(){
    var el;
    el = just.byId('addclass');
    just.addClass('one two three', el);
    expect(el).toHaveClass('one');
    expect(el).toHaveClass('two');
    expect(el).toHaveClass('three');
  });
  x$('should add multiple classes when passed an array', function(){
    var el;
    el = just.byId('addclass');
    just.addClass(['first', 'second', 'third'], el);
    expect(el).toHaveClass('first');
    expect(el).toHaveClass('second');
    expect(el).toHaveClass('third');
  });
});
describe('just.removeClass', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    return setFixtures("<p id=\"removeclass\" class=\"foo bar baz\"></p>\n<p id=\"removeclass-multi\" class=\"one two three foo\"></p>\n<p id=\"removeclass-multi-again\" class=\"one two three foo\"></p>");
  });
  afterEach(function(){
    return just.byId.clearCache();
  });
  x$('should remove class', function(){
    var el;
    el = just.byId('removeclass');
    just.removeClass('foo', el);
    expect(el).not.toHaveClass('foo');
    expect(el).toHaveClass('bar');
    expect(el).toHaveClass('baz');
  });
  x$('should be curried', function(){
    var el, removeBaz;
    el = just.byId('removeclass');
    removeBaz = just.removeClass('baz');
    removeBaz(el);
    expect(el).not.toHaveClass('baz');
  });
  x$('should remove multiple classes', function(){
    var el;
    el = just.byId('removeclass-multi');
    just.removeClass('three two one', el);
    expect(el).not.toHaveClass('one');
    expect(el).not.toHaveClass('two');
    expect(el).not.toHaveClass('three');
  });
  x$('should remove multiple classes when argument is an array', function(){
    var el;
    el = just.byId('removeclass-multi-again');
    just.removeClass(['two', 'one', 'three'], el);
    expect(el).not.toHaveClass('one');
    expect(el).not.toHaveClass('two');
    expect(el).not.toHaveClass('three');
  });
});
describe('just.hasClass', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<div id=\"hasclass\" class=\"foo bar\"></div>\n<div id=\"noclass\"></div>");
  });
  x$('should test if element has class', function(){
    var el;
    el = just.byId('hasclass');
    expect(just.hasClass('foo', el)).toBe(true);
    expect(just.hasClass('baz', el)).toBe(false);
  });
  x$('should be curried', function(){
    var el1, el2, hasBar;
    el1 = just.byId('hasclass');
    el2 = just.byId('noclass');
    hasBar = just.hasClass('bar');
    expect(hasBar(el1)).toBe(true);
    expect(hasBar(el2)).toBe(false);
  });
});
describe('just.data', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"nodata\"></p>\n<p id=\"data\" data-foo=\"bar\"></p>");
  });
  x$('should retrieve data', function(){
    var el;
    el = just.byId('data');
    expect(just.data('foo', el)).toEqual('bar');
  });
  x$('should be curried', function(){
    var el, getFoo;
    el = just.byId('data');
    getFoo = just.data('foo');
    expect(getFoo(el)).toEqual('bar');
  });
});
describe('just.setData', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"setdata\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should set data attribute', function(){
    var el;
    el = just.byId('setdata');
    just.setData('foo', el, 'bar');
    expect(just.data('foo', el)).toEqual('bar');
  });
  x$('should be curried', function(){
    var el, setBar, setBazOnEl;
    el = just.byId('setdata');
    setBar = just.setData('bar');
    setBar(el, 'baz');
    expect(just.data('bar', el)).toEqual('baz');
    setBazOnEl = just.setData('baz', el);
    setBazOnEl('foobar');
    expect(just.data('baz', el)).toEqual('foobar');
  });
});
describe('just.attr', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<a id=\"gethref\" href=\"http://example.com/\" title=\"Example\"></a>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return html attribute', function(){
    var el;
    el = just.byId('gethref');
    expect(just.attr('href', el)).toEqual('http://example.com/');
  });
  x$('should be curried', function(){
    var el, title;
    el = just.byId('gethref');
    title = just.attr('title');
    expect(title(el)).toEqual('Example');
  });
});
describe('just.setAttr', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<a id=\"sethref\"></a>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should set attribute on element', function(){
    var el;
    el = just.byId('sethref');
    just.setAttr('href', el, 'http://example.com/');
    expect(just.attr('href', el)).toEqual('http://example.com/');
  });
  x$('should be curried', function(){
    var el, setHref, setHrefOnEl;
    el = just.byId('sethref');
    setHref = just.setAttr('href');
    setHref(el, 'http://test.com/');
    expect(just.attr('href', el)).toEqual('http://test.com/');
    setHrefOnEl = just.setAttr('href', el);
    setHrefOnEl('http://www.test.com/');
    expect(just.attr('href', el)).toEqual('http://www.test.com/');
  });
});
describe('just.hasAttr', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<a id=\"nohref\"></a>\n<a id=\"hashref\" href=\"http://test.com/\"></a>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return true if element has attribute', function(){
    var el1, el2;
    el1 = just.byId('nohref');
    el2 = just.byId('hashref');
    expect(just.hasAttr('href', el1)).toBe(false);
    expect(just.hasAttr('href', el2)).toBe(true);
  });
  x$('should be curried', function(){
    var el1, el2, hasHref;
    el1 = just.byId('nohref');
    el2 = just.byId('hashref');
    hasHref = just.hasAttr('href');
    expect(hasHref(el1)).toBe(false);
    expect(hasHref(el2)).toBe(true);
  });
});