// Generated by LiveScript 1.2.0
describe('just.matchClass', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"hasfoo\" class=\"foo\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return element if it has matching class', function(){
    var el;
    el = just.byId('hasfoo');
    expect(just.matchClass('foo', el)).toBe(el);
    expect(just.matchClass('bar', el)).toBe(void 8);
  });
  x$('should be curried', function(){
    var el, hasFoo;
    el = just.byId('hasfoo');
    hasFoo = just.matchClass('foo');
    expect(hasFoo(el)).toBe(el);
  });
  x$('should not return anything if nothing is passed', function(){
    expect(just.matchClass('foo', null)).toBe(void 8);
  });
});
describe('just.matchAttr', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"hastitle\" title=\"foo\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return true if element has matching attribute', function(){
    var el;
    el = just.byId('hastitle');
    expect(just.matchAttr('title', 'foo', el)).toBe(el);
    expect(just.matchAttr('title', 'bar', el)).toBe(void 8);
  });
  x$('should return false for non-existent attributes', function(){
    var el;
    el = just.byId('hastitle');
    expect(just.matchAttr('href', 'http://example.com/', el)).toBe(void 8);
  });
  x$('should be curried', function(){
    var el, matchTitle, matchFoo;
    el = just.byId('hastitle');
    matchTitle = just.matchAttr('title');
    expect(matchTitle('foo', el)).toBe(el);
    expect(matchTitle('bar', el)).toBe(void 8);
    matchFoo = just.matchAttr('title', 'foo');
    expect(matchFoo(el)).toBe(el);
  });
  x$('should not return anything if nothing is passed', function(){
    expect(just.matchAttr('foo', 'bar', null)).toBe(void 8);
  });
});
describe('just.matchSelector', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"foo\" class=\"foo\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return element if it matches selector', function(){
    var el;
    el = just.byId('foo');
    expect(just.matchSelector('p.foo', el)).toBe(el);
    expect(just.matchSelector('div.foo', el)).toBe(void 8);
  });
  x$('should be curried', function(){
    var el, isPFoo;
    el = just.byId('foo');
    isPFoo = just.matchSelector('p.foo');
    expect(isPFoo(el)).toBe(el);
  });
  x$('should not return anything if nothing is passed', function(){
    expect(just.matchSelector('bar', null)).toBe(void 8);
  });
});
describe('just.matchAll', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p id=\"foo\" class=\"bar\" title=\"baz\"></p>\n<p id=\"notfoo\" class=\"baz\" title=\"bar\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return the element if it matches all matchers', function(){
    var el, matchBar, matchBaz, matchSelector, matchers;
    el = just.byId('foo');
    matchBar = just.matchClass('bar');
    matchBaz = just.matchAttr('title', 'baz');
    matchSelector = just.matchSelector('p#foo');
    matchers = [matchBar, matchBaz, matchSelector];
    expect(just.matchAll(matchers, el)).toBe(el);
  });
  x$('should return nothing if at least one matcher fails', function(){
    var el, matchBar, matchBaz, matchSelector, matchers;
    el = just.byId('foo');
    matchBar = just.matchClass('bar');
    matchBaz = just.matchAttr('title', 'baz');
    matchSelector = just.matchSelector('div#foo');
    matchers = [matchBar, matchBaz, matchSelector];
    expect(just.matchAll(matchers, el)).toBe(void 8);
  });
  x$('should be curried', function(){
    var el1, el2, matchBar, matchBaz, matchBarBaz;
    el1 = just.byId('foo');
    el2 = just.byId('notfoo');
    matchBar = just.matchClass('bar');
    matchBaz = just.matchAttr('title', 'baz');
    matchBarBaz = just.matchAll([matchBar, matchBaz]);
    expect(matchBarBaz(el1)).toBe(el1);
    expect(matchBarBaz(el2)).toBe(void 8);
  });
  x$('should return nothing if nothing is passed', function(){
    var matchBar, matchBaz, matchers;
    matchBar = just.matchClass('bar');
    matchBaz = just.matchAttr('title', 'baz');
    matchers = [matchBar, matchBaz];
    expect(just.matchAll(matchers, null)).toBe(void 8);
  });
});
describe('just.filter', function(){
  var x$;
  x$ = it;
  beforeEach(function(){
    setFixtures("<p class=\"foo\" title=\"bar\"></p>\n<p class=\"foo\" title=\"bar\"></p>\n<p class=\"foo\" title=\"bar\"></p>\n<p class=\"bar\" title=\"foo\"></p>");
  });
  afterEach(function(){
    just.byId.clearCache();
  });
  x$('should return a filtered list of elements', function(){
    var elements, matchFoo, matchBar, matchers, filtered;
    elements = just.byTag('p', document);
    matchFoo = just.matchClass('foo');
    matchBar = just.matchAttr('title', 'bar');
    matchers = [matchFoo, matchBar];
    filtered = just.filter(matchers, elements);
    expect(filtered.length).toEqual(3);
  });
  x$('should return empty array if no element matches', function(){
    var elements, matchBar, matchBaz, matchers, filtered;
    elements = just.byTag('p', document);
    matchBar = just.matchClass('bar');
    matchBaz = just.matchAttr('title', 'baz');
    matchers = [matchBar, matchBaz];
    filtered = just.filter(matchers, elements);
    expect(filtered.length).toEqual(0);
  });
  x$('should return nothing if matchers are missing', function(){
    var elements;
    elements = just.byTag('p', document);
    expect(just.filter([], elements)).toEqual(void 8);
    expect(just.filter(null, elements)).toEqual(void 8);
  });
  x$('should return nothing if elements are missing', function(){
    var matchFoo, matchBar, matchers;
    matchFoo = just.matchClass('foo');
    matchBar = just.matchAttr('title', 'bar');
    matchers = [matchFoo, matchBar];
    expect(just.filter(matchers, [])).toEqual(void 8);
    expect(just.filter(matchers, null)).toEqual(void 8);
  });
  x$('should be curried', function(){
    var elements, matchFoo, matchBar, matchers, filterFooBar, filtered;
    elements = just.byTag('p', document);
    matchFoo = just.matchClass('foo');
    matchBar = just.matchAttr('title', 'bar');
    matchers = [matchFoo, matchBar];
    filterFooBar = just.filter(matchers);
    filtered = filterFooBar(elements);
    expect(filtered.length).toEqual(3);
  });
});