// Generated by LiveScript 1.2.0
var define;
define = function(root){
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    return function(factory){
      var ref$;
      return import$((ref$ = root.just) != null
        ? ref$
        : root.just = {}, factory(function(){
        return root.just;
      }));
    };
  }
}(this);
define(function(require){
  var helpers, IS_BUBBLING, IS_CANCELABLE, NOT_CANCELLED, NO_CAPTURE, EVENT_TYPES, trigger, addListener, removeListener, evt;
  helpers = require('./helpers');
  IS_BUBBLING = true;
  IS_CANCELABLE = true;
  NOT_CANCELLED = true;
  NO_CAPTURE = false;
  return {
    EVENT_TYPES: EVENT_TYPES = {
      blur: 'FocusEvent',
      change: 'Event',
      click: 'MouseEvent',
      dblclick: 'MouseEvent',
      drag: 'DragEvent',
      dragend: 'DragEvent',
      dragenter: 'DragEvent',
      dragleave: 'DragEvent',
      dragover: 'DragEvent',
      dragstart: 'DragEvent',
      drop: 'DragEvent',
      focus: 'FocusEvent',
      keydown: 'KeyboardEvent',
      keypress: 'KeyboardEvent',
      keyup: 'KeyboardEvent',
      mousedown: 'MouseEvent',
      mouseenter: 'MouseEvent',
      mouseleave: 'MouseEvent',
      mousemove: 'MouseEvent',
      mouseout: 'MouseEvent',
      mouseup: 'MouseEvent',
      resize: 'UIEvent',
      scroll: 'UIEvent',
      select: 'UIEvent',
      storage: 'StorageEvent',
      submit: 'Event',
      touchcancel: 'TouchEvent',
      touchen: 'TouchEvent',
      touchenter: 'TouchEvent',
      touchleave: 'TouchEvent',
      touchmove: 'TouchEvent',
      touchstart: 'TouchEvent',
      unload: 'UIEvent'
    },
    trigger: trigger = curry$(function(eventName, el){
      var ref$, TEXT, COMMENT, data, e, type;
      ref$ = helpers.NODE_TYPES, TEXT = ref$.TEXT, COMMENT = ref$.COMMENT;
      if ((ref$ = el.nodeType) === TEXT || ref$ === COMMENT) {
        return;
      }
      data = arguments[2];
      if (document.createEventObject != null) {
        e = document.createEventObject();
        if (data != null) {
          import$(e, data);
        }
        el.fireEvent("on" + eventName, e, NOT_CANCELLED);
      } else {
        type = EVENT_TYPES[eventName] || 'Event';
        e = document.createEvent(type);
        e.initEvent(eventName, IS_BUBBLING, IS_CANCELABLE);
        if (data != null) {
          import$(e, data);
        }
        el.dispatchEvent(e);
      }
    }),
    addListener: addListener = curry$(function(eventName, el, fn){
      if (el.attachEvent != null) {
        el.attachEvent("on" + eventName, fn);
      } else if (el.addEventListener != null) {
        el.addEventListener(eventName, fn, NO_CAPTURE);
      } else {
        el["on" + eventName] = fn;
      }
    }),
    removeListener: removeListener = curry$(function(eventName, el, fn){
      if (el.detachEvent != null) {
        el.detachEvent("on" + eventName, fn);
      } else if (el.removeEventListener != null) {
        el.removeEventListener(eventName, fn, NO_CAPTURE);
      } else {
        if (el["on" + eventName] === fn) {
          el["on" + eventName] = null;
        }
      }
    }),
    evt: evt = function(e, defaultPrevented, noBubbling){
      e.target == null && (e.target = e.srcElement);
      e.preventDefault == null && (e.preventDefault = function(){
        return this.returnValue = false;
      });
      e.stopPropagation == null && (e.stopPropagation = function(){
        return this.cancelBubble = true;
      });
      e.which == null && (e.which = e.keyCode);
      e.keyCode == null && (e.keyCode = e.which);
      if (e.which != null) {
        e.keyChar = String.fromCharCode(e.which);
      }
      if (defaultPrevented) {
        e.preventDefault();
      }
      if (noBubbling) {
        e.stopPropagation();
      }
      return e;
    }
  };
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
function curry$(f, bound){
  var context,
  _curry = function(args) {
    return f.length > 1 ? function(){
      var params = args ? args.concat() : [];
      context = bound ? context || this : this;
      return params.push.apply(params, arguments) <
          f.length && arguments.length ?
        _curry.call(context, params) : f.apply(context, params);
    } : f;
  };
  return _curry();
}