// Generated by LiveScript 1.2.0
var define, slice$ = [].slice;
define = function(root){
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    return function(factory){
      var ref$;
      return import$((ref$ = root.just) != null
        ? ref$
        : root.just = {}, factory());
    };
  }
}(this);
define(function(){
  var NODE_TYPES, camelize;
  return {
    NODE_TYPES: NODE_TYPES = {
      ELEMENT: 1,
      ATTRIBUTE: 2,
      TEXT: 3,
      CDATA_SECTION: 4,
      ENTITY_REFERENCE: 5,
      ENTITY: 6,
      PROCESSING_INSTRUCTION: 7,
      COMMENT: 8,
      DOCUMENT: 9,
      DOCUMENT_TYPE: 10,
      DOCUMENT_FRAGMENT: 11,
      NOTATION: 12
    },
    camelize: camelize = function(s){
      var ref$, first, rest, r;
      ref$ = s.split(/[-_]/), first = ref$[0], rest = slice$.call(ref$, 1);
      return first + (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = rest).length; i$ < len$; ++i$) {
          r = ref$[i$];
          results$.push(r[0].toUpperCase() + r.slice(1));
        }
        return results$;
      }()).join('');
    }
  };
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}