// Generated by LiveScript 1.2.0
var define, slice$ = [].slice;
define = function(root){
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    return function(factory){
      var ref$;
      return import$((ref$ = root.utils) != null
        ? ref$
        : root.utils = {}, factory());
    };
  }
}(this);
define(function(){
  var camelize;
  return {
    camelize: camelize = function(s){
      var ref$, first, rest, r;
      ref$ = s.split(/[-_]/), first = ref$[0], rest = slice$.call(ref$, 1);
      return first + (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = rest).length; i$ < len$; ++i$) {
          r = ref$[i$];
          results$.push(r[0].toUpperCase() + r.slice(1));
        }
        return results$;
      }()).join('');
    }
  };
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}