// Generated by LiveScript 1.2.0
var define;
define = function(root){
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    return function(factory){
      var ref$;
      return import$((ref$ = root.utils) != null
        ? ref$
        : root.utils = {}, factory());
    };
  }
}(this);
define(function(){
  var remove;
  return {
    remove: remove = function(el){
      var i$, len$, e;
      if (el == null) {
        return;
      }
      if (el.length) {
        for (i$ = 0, len$ = el.length; i$ < len$; ++i$) {
          e = el[i$];
          remove(e);
        }
      } else {
        el.parentNode.removeChild(el);
      }
    }
  };
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}